import mongoose from "mongoose";
const preguntaSchema = new mongoose.Schema({
   enunciado:{
      type:String,
      required:true
   },
   tipoPregunta:{
      type:String,
      enum:[ "opcion_multiple", "verdadero_falso", "respuesta_corta" ],
      required:true
   },
   materia:{
      type:mongoose.Schema.Types.ObjectId,
      ref:"Materia",
      required:true
   },
   tema:{
      type:mongoose.Schema.Types.ObjectId,
      ref:"Tema",
      required:true
   },
   opciones:[String],
   respuestaCorrecta:{
      type:String,
      required:true
   },
   recursoApoyo:{
      tipo:{
         type:String,
         enum:["imagen","video","pdf","enlace"],
         default:null
      },
      url:{
         type:String,
         default:null
      }
   },
   explicacion:String,
   nivelDificultad:{
      type:String,
      enum:["facil","medio","dificil"],
      default:"medio"
   },
   estado:{
      type:Boolean,
      default:true
   }
},{
   timestamps:true
});
export default mongoose.model("Pregunta",preguntaSchema);